ARABIC_TESTS = {
    "A1": [
        ("“كِتاب” so‘zining ma’nosi nima?", ["Ruchka", "Kitob", "Qog‘oz"], 1),
        ("Arab alifbosida birinchi harf qaysi?", ["ب", "أ", "ت"], 1),
        ("“أنا طالب” qanday tarjima qilinadi?", ["Men o‘qituvchiman", "Menda maktab bor", "Men talabaman"], 2),
        ("“مَدْرَسَة” so‘zining ma’nosi qaysi?", ["Universitet", "Maktab", "Shifoxona"], 1),
        ("Arab alifbosida nechta harf bor?", ["28", "26", "30"], 0),
        ("“السلام عليكم” ning ma’nosi nima?", ["Salom", "Xush kelibsiz", "Sizga tinchlik bo‘lsin"], 2),
        ("“هي” so‘zining o‘zbekcha tarjimasi qaysi?", ["Sen", "U (qiz)", "U (o‘g‘il)"], 1),
        ("“باب” so‘zining ma’nosi qaysi?", ["Deraza", "Eshik", "Devor"], 1),
        ("“قلم” so‘zining ko‘pligi qaysi?", ["أقلام", "أقلمة", "قلمين"], 0),
        ("“شكراً” ning ma’nosi nima?", ["Xayr", "Rahmat", "Kechirasiz"], 1),
        ("“هو يدرس” ning tarjimasi qaysi?", ["U o‘qiydi", "U yozadi", "U o‘qituvchi"], 0),
        ("Qaysi so‘z “o‘rindiq” degani?", ["طاولة", "كرسي", "بيت"], 1),
        ("“ماء” nima?", ["Suv", "Non", "Choy"], 0),
        ("“أنا” ning ma’nosi qaysi?", ["Men", "Sen", "U"], 0),
        ("“بيت” so‘zining ma’nosi qaysi?", ["Maktab", "O‘yin", "Uy"], 2),
        ("Qaysi so‘z “shahar”ni anglatadi?", ["مدينة", "قرية", "شارع"], 0),
        ("“جميل” so‘zi nima degani?", ["Ko‘rkam / chiroyli", "Aqlli", "To‘g‘ri"], 0),
        ("“قميص” so‘zining ma’nosi qaysi?", ["Shim", "Ko‘ylak", "Oyoq kiyim"], 1),
        ("“هو” so‘zining ma’nosi qaysi?", ["U (qiz)", "U (o‘g‘il)", "Sen"], 1),
        ("“أين تسكن؟” degani nima?", ["Siz qayerda yashaysiz?", "Siz nima qilasiz?", "Siz kimsiz?"], 0),
        ("“الساعة” so‘zi nima?", ["Telefon", "Soat", "Kalendar"], 1),
        ("“غداء” ning ma’nosi qaysi?", ["Nonushta", "Tushlik", "Kechki ovqat"], 1),
        ("Qaysi so‘z “maktab” demak?", ["مدرسة", "مستشفى", "سيارة"], 0),
        ("“هو يكتب” ning ma’nosi qaysi?", ["U o‘qiydi", "U yozadi", "U eshitadi"], 1),
        ("“عائلة” so‘zining ma’nosi qaysi?", ["Mehmon", "Oila", "Jamoa"], 1),
        ("“مطبخ” qayer?", ["Yotoqxona", "Oshxona", "Hojatxona"], 1),
        ("Qaysi so‘z “ism” degani?", ["اسم", "عمل", "بلد"], 0),
        ("“متى؟” degani nima?", ["Qayerda?", "Qachon?", "Nima?"], 1),
        ("“يذهب” ning ma’nosi qaysi?", ["Boradi", "Keladi", "Qo‘yadi"], 0),
        ("“مع السلامة” ning ma’nosi nima?", ["Rahmat", "Xayr / salomat bo‘ling", "Iltimos"], 1),
    ],
    "A2": [
        ("“أنتما تذهبان إلى السوق.” jumlasida “تذهبان” qanday ma’noda kelgan?", ["Ular boradi", "Ikkalangiz boryapsiz", "Sen boryapsan"], 1),
        ("“أين تعمل والدتك؟” ning to‘g‘ri tarjimasi qaysi?", ["Onang qayerda o‘qiydi?", "Onang qayerga ketdi?", "Onang qayerda ishlaydi?"], 2),
        ("“الطفل يشرب الحليب.” jumlasi nimani bildiradi?", ["Bola sut ichyapti", "Bola uyga ketyapti", "Bola yozyapti"], 0),
        ("“أنا لا أحب القهوة.” ning ma’nosi qaysi?", ["Men qahvani yaxshi ko‘raman", "Men qahva ichaman", "Men qahvani yaxshi ko‘rmayman"], 2),
        ("“متى تبدأ الحصة؟” nima degani?", ["Dars qachon tugaydi?", "Dars qachon boshlanadi?", "Dars qayerda?"], 1),
        ("“هو يذهب إلى المدرسة كل يوم.” jumlasining tarjimasi qaysi?", ["U har kuni ishga boradi", "U har kuni maktabga boradi", "U har kuni uyda qoladi"], 1),
        ("“الكتاب على الطاولة.” nima degani?", ["Kitob stolning ichida", "Kitob polda", "Kitob stol ustida"], 2),
        ("“أنا ذهبت إلى السوق البارحة.” jumlasining tarjimasi qaysi?", ["Men bozorga ertaga boraman", "Men kecha bozorga bordim", "Men hozir bozordaman"], 1),
        ("“هل تحب الرياضة؟” savoliga “نعم، أحبها” qanday javob?", ["Yo‘q, yoqmaydi", "Ha, yaxshi ko‘raman", "Balki"], 1),
        ("“أنا أتكلم العربية قليلاً.” ning ma’nosi qaysi?", ["Men arab tilini yaxshi bilaman", "Men arab tilida ozgina gapiraman", "Men arab tilida yozaman"], 1),
        ("Qaysi jumla o‘tgan zamonda keltirilgan?", ["هو يدرس", "هو درس", "هو يذهب"], 1),
        ("“نحن نكتب الدرس الآن.” jumlasida fe’l qaysi?", ["نكتب", "الدرس", "الآن"], 0),
        ("“السيارة أمام البيت.” ning ma’nosi qaysi?", ["Mashina uy ortida", "Mashina uy oldida", "Mashina uy ichida"], 1),
        ("“أنا أعيش في طشقند.” jumlasida qaysi fe’l kelgan?", ["أكتب", "أعيش", "أذهب"], 1),
        ("“هل عندك إخوة؟” savolining ma’nosi qaysi?", ["Sizning aka-ukalaringiz bormi?", "Sizning farzandlaringiz bormi?", "Sizning do‘stingiz bormi?"], 0),
        ("“هو يعمل طبيبًا.” nima degani?", ["U shifokor bo‘lib ishlaydi", "U bemor", "U talaba"], 0),
        ("“أنا قرأت الكتاب.” qaysi zamonda keltirilgan?", ["Hozirgi", "Kelajak", "O‘tgan"], 2),
        ("“الجو حار اليوم.” nima degani?", ["Bugun sovuq", "Bugun iliq", "Bugun issiq"], 2),
        ("“هي طالبة ذكية.” jumlasida qaysi so‘z “aqlli” ma’nosini beradi?", ["طالبة", "ذكية", "هي"], 1),
        ("“نذهب إلى الحديقة غدًا.” nima degani?", ["Biz bog‘ga kecha bordik", "Biz bog‘ga bugun boramiz", "Biz bog‘ga ertaga boramiz"], 2),
        ("“أين تسكنون؟” savoliga qaysi javob mos?", ["ندرس في المدرسة", "نسكن في طشقند", "نأكل في البيت"], 1),
        ("“ماذا تفعل في عطلة نهاية الأسبوع؟” savoli nima haqida?", ["Ish haqida", "Maktab haqida", "Hafta oxirida nima qilishingiz haqida"], 2),
        ("“أنا مشغول الآن.” nima degani?", ["Men hozir dam olyapman", "Men hozir bandman", "Men hozir ketyapman"], 1),
        ("“أختي تحب القراءة.” nima degani?", ["Singlim o‘ynashni yoqtiradi", "Singlim ovqat tayyorlaydi", "Singlim o‘qishni yoqtiradi"], 2),
        ("“ما هوايتك؟” savoliga qaysi javob to‘g‘ri?", ["كرة القدم", "جامعة", "مستشفى"], 0),
        ("“هل تحب القطة؟” savoliga qaysi javob to‘g‘ri?", ["نعم، أحبها", "لا، أنا سيارة", "نعم، هو ولد"], 0),
        ("“أين يعمل والدك؟” savoliga qaysi javob to‘g‘ri?", ["هو يلعب في البيت", "هو يعمل في بنك", "هو في المدرسة"], 1),
        ("“متى تستيقظ؟” nima degani?", ["Qachon uxlaysiz?", "Qachon turasiz?", "Qachon ovqatlanasiz?"], 1),
        ("“أنا أدرس اللغة العربية.” ning to‘g‘ri tarjimasi qaysi?", ["Men arab tilini o‘rganaman", "Men arab tilini o‘rgataman", "Men arab tilini unutdim"], 0),
        ("“الولد يركض في الحديقة.” jumlasida nima bo‘lyapti?", ["Bola bog‘da yuryapti", "Bola bog‘da yuguryapti", "Bola bog‘da uxlayapti"], 1),
    ],
}
