KOREAN_TESTS = {
    "O‘rta": [
        ("“안녕하세요” so‘zining ma’nosi qaysi?", ["Xayr", "Salom", "Rahmat", "Kechirasiz"], 1),
        ("“감사합니다” qanday tarjima qilinadi?", ["Rahmat", "Salom", "Uy", "Maktab"], 0),
        ("Koreys tilida “men” ma’nosidagi so‘z qaysi?", ["나", "너", "우리", "그"], 0),
        ("“학교” so‘zining ma’nosi nima?", ["Do‘kon", "Maktab", "Uy", "Kitob"], 1),
        ("“책” so‘zining ma’nosi qaysi?", ["Kitob", "Ruchka", "Stol", "Telefon"], 0),
        ("“물” nima degani?", ["Non", "Suv", "Choy", "Ovqat"], 1),
        ("“저는 학생입니다” jumlasi qanday tarjima qilinadi?", ["Men o‘qituvchiman", "Men talabaman", "Men shifokorman", "Men uyda"], 1),
        ("Koreys tilida hurmatli gap oxiri ko‘pincha qaysi bilan tugaydi?", ["-요 / -습니다", "-lar", "-ing", "-ning"], 0),
        ("“어디에 가요?” nima degani?", ["Qayerga borasiz?", "Nima yeysiz?", "Qachon kelasiz?", "Kim bilan? "], 0),
        ("“오늘” so‘zining ma’nosi qaysi?", ["Kecha", "Bugun", "Ertaga", "Hozir"], 1),
        ("“내일” nima degani?", ["Ertaga", "Bugun", "Kecha", "Avval"], 0),
        ("“먹다” fe’lining ma’nosi qaysi?", ["Ichmoq", "Yemoq", "Bormoq", "Ko‘rmoq"], 1),
        ("“가다” fe’lining ma’nosi nima?", ["Kelmoq", "Bormoq", "O‘qimoq", "Yozmoq"], 1),
        ("“보다” fe’lining ma’nosi qaysi?", ["Ko‘rmoq", "Eshitmoq", "Yemoq", "Uxlash"], 0),
        ("“친구” so‘zining ma’nosi nima?", ["Oila", "Do‘st", "Ustoz", "Talaba"], 1),
        ("“집에 있어요” jumlasi qanday tarjima qilinadi?", ["Uyda bor", "Uyda turibman/boraman", "Uyda boraman", "Uyda ishlayman"], 0),
        ("“한국어를 공부해요” jumlasi nimani bildiradi?", ["Koreys tilini o‘rganaman", "Koreyaga boraman", "Koreys ovqatini yeyman", "Koreyscha yozmayman"], 0),
        ("Koreys tilida savol tuzishda ohangdan tashqari qaysi qo‘shimcha ko‘p uchraydi?", ["-까?", "-lar", "-dan", "-ni"], 0),
        ("“몇 시예요?” nima degani?", ["Soat nechchi?", "Qayerdasiz?", "Ismingiz nima?", "Nima qilyapsiz?"], 0),
        ("“괜찮아요” so‘zining ma’nosi qaysi?", ["Hammasi joyida / yaxshi", "Tez boring", "Men bilmayman", "Sovuq"], 0),
    ],
}
