from .seed_arabic import ARABIC_TESTS
from .seed_it import IT_TESTS
from .seed_korean import KOREAN_TESTS
from .seed_math import MATH_TESTS
from .seed_mental import MENTAL_TESTS
from .seed_office import OFFICE_TESTS


RUSSIAN_TESTS = {
    "A1": [
        ("Найдите имя существительное.", ["красивый", "быстро", "телефон", "читать"], 2),
        ("Как правильно сказать?", ["Я читать", "Я прочитаем", "Я прочитал", "Я прочти"], 2),
        ("Найдите личные местоимения в именительном падеже.", ["мой, твой, наш, ваш, их", "меня, тебя, нас, вас, их", "я, ты, он, мы, вы, они", "я, тебя, мой, ты"], 2),
        ("В каком слове есть удвоенная согласная?", ["лист", "шоссе", "маркер", "стол"], 1),
        ("Это книга…", ["моей друга", "моему другу", "моего друга", "мой друг"], 2),
        ("Сколько падежей в русском языке?", ["5", "7", "4", "6"], 3),
        ("Мы зашли в кафе, чтобы спрятаться…", ["с дождём", "к дождю", "от дождя", "в дождь"], 2),
        ("На какие вопросы отвечает имя существительное в именительном падеже?", ["кого? чего?", "кто? чего?", "кто? что?", "кому? чему?"], 2),
        ("Какое слово является глаголом?", ["сладко", "хороший", "говорить", "быстро"], 2),
        ("Сколько … вы там будете?", ["день", "дня", "дней", "от дня"], 2),
        ("Я хочу купить … сумку.", ["меньший", "маленькую", "маленький", "маленькие"], 1),
        ("Мария купила швейцарские…", ["сувенир", "шоколад", "часы", "книга"], 2),
        ("Надо извиниться … за неудобство.", ["от него", "к нему", "перед ним", "с ним"], 2),
        ("Учебный центр находится…", ["города", "городам", "в городе", "на городе"], 2),
        ("Сколько родов в русском языке?", ["5", "3", "6", "4"], 1),
        ("Что обозначает имя прилагательное?", ["предмет", "действие предмета", "признак предмета", "число"], 2),
        ("Павел приехал…", ["в суббота", "на субботу", "в субботу", "суббота"], 2),
        ("Студенты … в университет.", ["едем", "едешь", "еду", "едут"], 3),
        ("В каком предложении есть ошибка?", ["Мы давно видите друг друга.", "У меня новая машина.", "Я люблю читать сказки.", "Я изучаю русский язык."], 0),
        ("Найдите имя прилагательное.", ["быстро", "умный", "маркер", "чистить"], 1),
    ],
    "A2": [
        ("Мы поедем путешествовать…", ["к будущей неделе", "будущая неделя", "на будущей неделе", "на будущую неделя"], 2),
        ("У меня болит нога, завтра я пойду…", ["хирург", "у хирургу", "к хирургу", "хирургу"], 2),
        ("Лена идёт в библиотеку … книгу.", ["изучать", "выучить", "читать", "написал"], 2),
        ("Что обозначает глагол?", ["признак предмета", "свойство предмета", "действие предмета", "число"], 2),
        ("Алишер не заметил … и прошёл мимо.", ["нами", "как", "нас", "нам"], 2),
        ("Какое слово является числительным?", ["бегать", "красиво", "шесть", "умный"], 2),
        ("Сколько падежей в русском языке?", ["5", "3", "6", "4"], 2),
        ("Найдите глагол совершенного вида.", ["читать", "ходить", "прочитать", "бегать"], 2),
        ("В каком предложении есть глагол несовершенного вида?", ["Он прочитал эту книгу.", "Она хочет поехать в Москву.", "Он ходит в школу каждый день.", "Мы приехали на море."], 2),
        ("Какой вариант правильный?", ["Он читал книга.", "Он читать книгу.", "Он читает книгу.", "Он читают книгу."], 2),
        ("Сколько родов в русском языке?", ["6", "4", "3", "5"], 2),
        ("Какое действие обозначает глагол совершенного вида?", ["незаконченное действие", "признак действия", "завершённое действие", "действие предмета"], 2),
        ("В каком варианте перечислены только имена существительные?", ["ребёнок, цветок, бегать, машина", "красивый, цветной, умный, смелый", "стол, телефон, сумка, маркер", "ручка, фен, искусственный, ужинать"], 2),
        ("В каком варианте перечислены существительные общего рода?", ["мама, тётя, папа, сын", "умница, сирота, неряха, задира", "учитель, студент, домохозяйка, маркер", "книга, телефон, карандаши, ручка"], 1),
        ("В каком слове есть удвоенная согласная?", ["лист", "масса", "ветер", "снег"], 1),
        ("Вчера я … письмо маме и отправил его.", ["взять", "получаю", "посылаю", "написал"], 3),
        ("Сколько букв в русском алфавите?", ["31", "29", "33", "28"], 2),
        ("Что обозначает имя числительное?", ["предмет", "признак", "число", "действие"], 2),
        ("Вот ключ. Смотри, не … его.", ["терять", "найди", "потеряй", "отдай"], 2),
        ("Я ещё не … работу. Подожди меня.", ["заканчивать", "сделать", "закончил", "делать"], 2),
    ],
    "B1": [
        ("Если бы у меня было время, я … на курсы рисования.", ["запишусь", "записался бы", "записываюсь", "буду записаться"], 1),
        ("Какое слово пропущено? Он так и не привык … рано по утрам.", ["вставанию", "вставать", "вставая", "встать"], 1),
        ("Я зашёл к другу … учебником.", ["по", "за", "с", "для"], 1),
        ("Преподаватель попросил студентов, чтобы они … словари.", ["принесут", "принесли", "приносят", "приносить"], 1),
        ("Выберите антоним к слову «редко».", ["всегда", "иногда", "быстро", "часто"], 3),
        ("Какое из выражений означает «очень быстро»?", ["как снег на голову", "не в своей тарелке", "сломя голову", "спустя рукава"], 2),
        ("Я не знаю, …", ["если он придёт на встречу", "что он придёт на встречу", "будет он на встрече", "придёт ли он на встречу"], 3),
        ("Мы восхищаемся этим талантлив… артистом.", ["-ого", "-ом", "-ым", "-ый"], 2),
        ("Вчера я … фильм, который мне советовали.", ["смотрел", "вижу", "глядел", "посмотрел"], 3),
        ("У меня нет … рублей.", ["пятисот", "пятьсот", "пятистам", "пятиста"], 0),
        ("Мы гордимся нашими … учениками.", ["восьмиста", "восьмистам", "восемьюстами", "восемьсот"], 2),
        ("Выберите подходящий антоним к слову «полезный».", ["вредный", "бесполезный", "опасный", "нужный"], 1),
        ("Что обозначает фразеологизм «биться как рыба об лёд»?", ["упорно, но безрезультатно действовать", "хорошо плавать и любить зиму", "быть очень холодным человеком", "хранить молчание"], 0),
        ("Письмо, … вчера, уже доставлено.", ["написанное", "написанная", "пишущее", "написавшее"], 0),
        ("Завтра я обязательно … эту статью до конца.", ["дочитаю", "буду читать", "прочитываю", "читаю"], 0),
        ("Книга была … известным автором.", ["написала", "писать", "написана", "написав"], 2),
        ("Я не пошёл на прогулку, … начался сильный дождь.", ["чтобы", "поэтому", "хотя", "потому что"], 3),
        ("В нашем городе много …", ["музее", "музей", "музеев", "музеи"], 2),
        ("Какое слово лишнее в этом ряду?", ["карандаш", "кресло", "диван", "стул"], 0),
        ("Он попросил меня … ему книгу через неделю.", ["вернуть", "верну", "возвращать", "вернёт"], 0),
    ],
}


ENGLISH_TESTS = {
    "Starter": [
        ("I ___ a student.", ["am", "is", "are", "be"], 0),
        ("She ___ my friend.", ["am", "is", "are", "be"], 1),
        ("They ___ teachers.", ["am", "is", "are", "be"], 2),
        ("___ this your book?", ["Am", "Is", "Are", "Be"], 1),
        ("This ___ a pen.", ["am", "is", "are", "be"], 1),
        ("These ___ my shoes.", ["am", "is", "are", "be"], 2),
        ("___ are my friends.", ["This", "That", "These", "It"], 2),
        ("___ is your bag (far from you).", ["This", "These", "That", "Those"], 2),
        ("I ___ a car.", ["have", "has", "having", "had"], 0),
        ("He ___ a bike.", ["have", "has", "having", "had"], 1),
        ("We ___ two cats.", ["has", "have", "having", "had"], 1),
        ("There ___ a book on the table.", ["is", "are", "am", "be"], 0),
        ("There ___ three chairs in the room.", ["is", "are", "am", "be"], 1),
        ("There ___ many students here.", ["is", "are", "am", "be"], 1),
        ("I see ___ apple.", ["a", "an", "the", "—"], 1),
        ("She has ___ dog.", ["a", "an", "the", "—"], 0),
        ("This is ___ orange.", ["a", "an", "the", "—"], 1),
        ("One book – two ___", ["book", "books", "bookes", "book’s"], 1),
        ("One child – two ___", ["childs", "childrens", "children", "childes"], 2),
        ("One box – two ___", ["boxs", "boxes", "box", "boxies"], 1),
    ],
    "Beginner": [
        ("She ___ from France.", ["am", "is", "are", "be"], 1),
        ("They ___ in a hotel.", ["is", "are", "am", "be"], 1),
        ("___ you got a car?", ["Have", "Has", "Are", "Is"], 0),
        ("This ___ my phone and those ___ my keys.", ["is / are", "are / is", "is / is", "are / are"], 0),
        ("I ___ coffee every morning.", ["drink", "drinks", "drinking", "drank"], 0),
        ("She ___ to work at 8.", ["go", "goes", "going", "went"], 1),
        ("We ___ TV in the evening.", ["watch", "watches", "watching", "watched"], 0),
        ("He ___ like pizza.", ["don’t", "doesn’t", "isn’t", "aren’t"], 1),
        ("___ you work on Sunday?", ["Do", "Does", "Are", "Is"], 0),
        ("I ___ get up at 7 every day.", ["usually", "yesterday", "now", "tomorrow"], 0),
        ("There ___ a bank near my house.", ["is", "are", "am", "be"], 0),
        ("There ___ many shops here.", ["is", "are", "am", "be"], 1),
        ("___ there a restaurant?", ["Is", "Are", "Am", "Be"], 0),
        ("She can ___ very well.", ["swim", "swims", "swimming", "swam"], 0),
        ("I like ___ music.", ["listen", "listens", "listening", "listened"], 2),
        ("He ___ play the guitar.", ["can", "cans", "caning", "caned"], 0),
        ("We ___ to the gym on Mondays.", ["go", "goes", "going", "went"], 0),
        ("She ___ coffee.", ["doesn’t like", "don’t like", "not like", "no like"], 0),
        ("___ you help me with this bag, please?", ["Can", "Do", "Are", "Is"], 0),
        ("They ___ in a big house.", ["live", "lives", "living", "lived"], 0),
    ],
    "Elementary": [
        ("She ___ got two brothers.", ["have", "has", "is", "are"], 1),
        ("I ___ usually get up at 7.", ["am", "do", "—", "does"], 2),
        ("There ___ a shop near my house.", ["is", "are", "am", "be"], 0),
        ("There ___ many people here.", ["is", "are", "am", "be"], 1),
        ("___ there a bank?", ["Is", "Are", "Do", "Does"], 0),
        ("I ___ TV now.", ["watch", "watches", "am watching", "watched"], 2),
        ("She ___ a book at the moment.", ["read", "reads", "is reading", "reading"], 2),
        ("He can ___ very well.", ["swim", "swims", "swimming", "swam"], 0),
        ("When we were younger, we ___ play football very well.", ["can", "could", "can’t", "couldn’t"], 1),
        ("I need ___ umbrella.", ["a", "an", "the", "—"], 1),
        ("She is ___ teacher.", ["a", "an", "the", "—"], 0),
        ("We live ___ a big city.", ["in", "on", "at", "to"], 0),
        ("He ___ to work by bus.", ["go", "goes", "going", "went"], 1),
        ("I ___ not like coffee.", ["do", "does", "don’t", "doesn’t"], 0),
        ("___ you working now?", ["Do", "Are", "Is", "Does"], 1),
        ("They ___ dinner at the moment.", ["have", "has", "are having", "had"], 2),
        ("We ___ English every day.", ["study", "studies", "studying", "studied"], 0),
        ("She ___ at home now.", ["is", "are", "am", "be"], 0),
        ("He ___ TV every day.", ["watch", "watches", "watching", "watched"], 1),
        ("I ___ coffee at the moment.", ["drink", "drinks", "am drinking", "drank"], 2),
    ],
    "Pre-Intermediate": [
        ("I ___ watching TV when he arrived.", ["was", "were", "am", "be"], 0),
        ("She ___ to Paris last summer.", ["go", "goes", "went", "going"], 2),
        ("We ___ visit our grandparents this weekend.", ["go to", "going to", "are going to", "went"], 2),
        ("It ___ rain tomorrow.", ["will", "did", "does", "was"], 0),
        ("I think she ___ pass the exam.", ["will", "did", "was", "has"], 0),
        ("There isn’t ___ milk in the fridge.", ["some", "any", "many", "a"], 1),
        ("There are ___ apples on the table.", ["much", "a", "many", "any"], 2),
        ("This book is ___ than that one.", ["interesting", "more interesting", "most interesting", "interest"], 1),
        ("It’s the ___ place I’ve ever visited.", ["beautiful", "more beautiful", "most beautiful", "beauty"], 2),
        ("I have ___ finished my homework.", ["yet", "already", "ago", "last"], 1),
        ("She hasn’t finished her work ___.", ["already", "yet", "ago", "last"], 1),
        ("We ___ lived here for five years.", ["have", "has", "did", "were"], 0),
        ("He ___ just arrived.", ["have", "has", "did", "was"], 1),
        ("I ___ seen that film before.", ["have", "has", "did", "was"], 0),
        ("They ___ dinner when we arrived.", ["have", "had", "were having", "are having"], 2),
        ("She ___ going to buy a new car.", ["is", "are", "am", "be"], 0),
        ("We ___ not go out yesterday.", ["didn’t", "don’t", "doesn’t", "not"], 0),
        ("I ___ probably stay at home tonight.", ["will", "did", "was", "have"], 0),
        ("This exercise is ___ than the previous one.", ["easy", "easier", "easiest", "more easy"], 1),
        ("That was the ___ film I’ve ever seen.", ["bad", "worse", "worst", "badly"], 2),
    ],
    "Intermediate": [
        ("I enjoy ___ films in my free time.", ["watch", "to watch", "watching", "watched"], 2),
        ("He promised ___ me later.", ["call", "calling", "to call", "called"], 2),
        ("I’ve just ___ my homework.", ["finish", "finished", "finishing", "finishes"], 1),
        ("She ___ her keys yesterday.", ["has lost", "lost", "loses", "losing"], 1),
        ("He ___ be at work now – it’s Sunday.", ["must", "can’t", "should", "might"], 1),
        ("If I ___ rich, I would travel the world.", ["am", "was", "were", "be"], 2),
        ("She used to ___ a lot when she was younger.", ["travel", "travels", "travelling", "traveled"], 0),
        ("I ___ finish this today; it’s very important.", ["must", "could", "might", "may"], 0),
        ("You ___ smoke here. It’s not allowed.", ["must", "mustn’t", "can", "should"], 1),
        ("I didn’t go out because I ___ studying.", ["was", "were", "am", "be"], 0),
        ("This is the man ___ helped me.", ["which", "who", "where", "whose"], 1),
        ("If you mix red and blue, you ___ purple.", ["get", "will get", "got", "getting"], 0),
        ("He asked me what I ___ doing.", ["am", "was", "were", "be"], 1),
        ("I’m interested in ___ new skills.", ["learn", "learning", "learned", "learns"], 1),
        ("She ___ already finished her work.", ["have", "has", "had", "having"], 1),
        ("I’ve lived here ___ five years.", ["since", "for", "from", "during"], 1),
        ("That exercise was ___ than the last one.", ["easy", "easier", "easiest", "more easy"], 1),
        ("This is ___ best restaurant in town.", ["a", "an", "the", "—"], 2),
        ("The problem ___ solved quickly yesterday.", ["was", "were", "is", "be"], 0),
        ("He speaks English very ___.", ["good", "well", "better", "best"], 1),
    ],
}


SEEDED_TESTS = {
    "Rus tili": RUSSIAN_TESTS,
    "Ingliz tili": ENGLISH_TESTS,
    "IT": IT_TESTS,
    "Kompyuter": OFFICE_TESTS,
    "Matematika": MATH_TESTS,
    "Arab tili": ARABIC_TESTS,
    "Koreys tili": KOREAN_TESTS,
    "Mental arifmetika": MENTAL_TESTS,
}
