PYTHON_TESTS = [
    ("Python dasturi faylining kengaytmasi qaysi?", [".js", ".html", ".py", ".exe"], 2),
    ("Ekranga ma'lumot chiqarish uchun qaysi funksiya ishlatiladi?", ["print()", "input()", "len()", "type()"], 0),
    ("Python tilida bir qatorli izoh qaysi belgi bilan boshlanadi?", ["//", "<!--", "/*", "#"], 3),
    ("O'zgaruvchiga qiymat biriktirish uchun qaysi operator ishlatiladi?", ["==", "=", ":=:", "=>"], 1),
    ("Quyidagi kodda x o'zgaruvchisining turi nima?\nx = 10", ["str", "float", "int", "bool"], 2),
    ("Foydalanuvchidan ma'lumot olish uchun qaysi funksiya ishlatiladi?", ["input()", "print()", "read()", "scan()"], 0),
    ("Python tilida if shartidan keyin qaysi belgi qo'yiladi?", [";", "{", ".", ":"], 3),
    ("Quyidagi kod natijasi nima?\nprint(7 // 2)", ["3.5", "3", "1", "4"], 1),
    ("Quyidagi kod natijasi nima?\nprint(7 % 2)", ["1", "2", "3", "3.5"], 0),
    ("Quyidagi kod natijasi nima?\nprint(2 ** 3)", ["6", "5", "8", "9"], 2),
    ("Quyidagi kod natijasi nima?\nsonlar = [2, 4, 6, 8]\nprint(len(sonlar))", ["3", "6", "8", "4"], 3),
    ("Ro'yxat oxiriga yangi element qo'shish uchun qaysi metod ishlatiladi?", ["add()", "append()", "push()", "insertEnd()"], 1),
    ("Python ro'yxatidagi birinchi element indeksi nechadan boshlanadi?", ["0", "1", "-1", "2"], 0),
    ("Quyidagi kod qaysi sonlarni chiqaradi?\nfor i in range(3):\n    print(i)", ["1, 2, 3", "0, 1, 2, 3", "0, 1, 2", "1, 2"], 2),
    ("Quyidagi kod natijasi nima?\ns = 0\nfor i in range(1, 4):\n    s += i\nprint(s)", ["3", "4", "5", "6"], 3),
    ("Shart rost bo'lib turgan vaqt davomida kodni takrorlash uchun qaysi sikl ishlatiladi?", ["for", "while", "if", "def"], 1),
    ("Python tilida funksiya yaratish uchun qaysi kalit so'z ishlatiladi?", ["def", "function", "func", "method"], 0),
    ("Funksiyadan qiymat qaytarish uchun qaysi kalit so'z ishlatiladi?", ["print", "break", "return", "yielding"], 2),
    ("Quyidagi kod natijasi nima?\nsonlar = [x * 2 for x in range(3)]\nprint(sonlar)", ["[2, 4, 6]", "[0, 1, 2]", "[1, 2, 3]", "[0, 2, 4]"], 3),
    ("Quyidagi kod natijasi nima?\nmatn = \"Python\"\nprint(matn[1:4])", ["Pyt", "yth", "ytho", "tho"], 1),
    ("Lug'at (dictionary) yaratishda asosan qaysi qavslar ishlatiladi?", ["{}", "[]", "()", "<>"], 0),
    ("Quyidagi lug'atdan ismni olishning to'g'ri usuli qaysi?\nuser = {\"name\": \"Ali\"}", ["user.name", "user(name)", "user[\"name\"]", "user->name"], 2),
    ("Tuple yaratish uchun odatda qaysi qavslar ishlatiladi?", ["{}", "[]", "<>", "()"], 3),
    ("Takrorlanmaydigan elementlar to'plamini saqlash uchun qaysi tur ishlatiladi?", ["list", "set", "tuple", "str"], 1),
    ("Quyidagi kod natijasi nima?\nprint(bool(0))", ["False", "True", "0", "None"], 0),
    ("Quyidagi kod natijasi nima?\nprint(True and False)", ["True", "None", "False", "0"], 2),
    ("Quyidagi kod natijasi nima?\nprint(False or True)", ["False", "None", "0", "True"], 3),
    ("math modulini dasturga ulashning to'g'ri ko'rinishi qaysi?", ["include math", "import math", "using math", "connect math"], 1),
    ("Dastur bajarilishidagi xatoni ushlab qolish uchun qaysi tuzilma ishlatiladi?", ["try / except", "if / else", "for / while", "def / return"], 0),
    ("Faylni o'qish rejimida ochish uchun qaysi kod to'g'ri?", ["open(\"data.txt\", \"w\")", "read(\"data.txt\")", "open(\"data.txt\", \"r\")", "file(\"data.txt\", \"read\")"], 2),
]
