OFFICE_TESTS = {
    "Word": [
        ("Word dasturida matnni qalin qilish uchun qaysi buyruq tanlanadi?", ["Вставка → Рисунки", "Макет → Поля", "Главная → Жирный", "Рецензирование → Перевести"], 2),
        ("Hujjatga rasm joylash uchun qaysi bo'lim ishlatiladi?", ["Вставка → Рисунки", "Главная → Заменить", "Вид → Линейка", "Файл → Сведения"], 0),
        ("Sahifa yo'nalishini kitob yoki albom ko'rinishiga almashtirish buyrug'i qaysi?", ["Конструктор → Цвет страницы", "Макет → Ориентация", "Вставка → Фигуры", "Главная → Абзац"], 1),
        ("Hujjatni saqlash uchun qaysi buyruq tanlanadi?", ["Файл → Открыть", "Файл → Печать", "Файл → Создать", "Файл → Сохранить"], 3),
        ("Matndan kerakli so'zni qidirish uchun qaysi buyruq ishlatiladi?", ["Главная → Найти", "Главная → Выделить", "Вставка → Символ", "Макет → Колонки"], 0),
        ("Bir so'zni boshqasiga avtomatik almashtirish uchun qaysi buyruq tanlanadi?", ["Вид → Масштаб", "Главная → Заменить", "Вставка → Ссылка", "Файл → Экспорт"], 1),
        ("Word hujjatiga jadval qo'shish uchun qaysi buyruq ishlatiladi?", ["Макет → Размер", "Главная → Стили", "Вставка → Таблица", "Конструктор → Подложка"], 2),
        ("Sahifaga xira fon yozuvi qo'yish uchun qaysi buyruq tanlanadi?", ["Вставка → Надпись", "Макет → Поля", "Главная → Шрифт", "Конструктор → Подложка"], 3),
        ("Sahifa fonining rangini o'zgartirish qayerda bajariladi?", ["Конструктор → Цвет страницы", "Вставка → Цвет", "Вид → Режим чтения", "Главная → Заливка"], 0),
        ("Sahifa atrofiga chegara qo'yish uchun qaysi buyruq ishlatiladi?", ["Макет → Отступ", "Конструктор → Границы страниц", "Вставка → Фигуры", "Главная → Границы"], 1),
        ("Matnni bir necha ustunga bo'lish uchun qaysi buyruq tanlanadi?", ["Главная → Сортировка", "Вставка → Таблица", "Макет → Колонки", "Вид → Несколько страниц"], 2),
        ("A4 kabi sahifa o'lchamini tanlash uchun qaysi buyruq ishlatiladi?", ["Вставка → Страница", "Файл → Параметры", "Конструктор → Эффекты", "Макет → Размер"], 3),
        ("Ekranda lineykani ko'rsatish yoki yashirish uchun qaysi buyruq ishlatiladi?", ["Вид → Линейка", "Главная → Показать все знаки", "Макет → Направляющие", "Рецензирование → Примечание"], 0),
        ("Hujjat xususiyatlari va himoyasi haqidagi ma'lumotlar qayerda joylashgan?", ["Главная → Стили", "Файл → Сведения", "Вставка → Объект", "Вид → Свойства"], 1),
        ("Hujjatga sana va vaqt qo'shish uchun qaysi buyruq tanlanadi?", ["Главная → Дата", "Макет → Время", "Вставка → Дата и время", "Файл → Сведения"], 2),
        ("Kompyuter ekranidan tasvir qo'shish uchun qaysi buyruq ishlatiladi?", ["Вид → Снимок", "Главная → Копировать", "Файл → Экспорт", "Вставка → Снимок"], 3),
        ("Tayyor geometrik shakl qo'shish uchun qaysi buyruq tanlanadi?", ["Вставка → Фигуры", "Главная → Границы", "Макет → Объекты", "Конструктор → Формы"], 0),
        ("Ma'lumotlarni grafik ko'rinishda berish uchun diagramma qayerdan qo'shiladi?", ["Главная → Диаграмма", "Вставка → Диаграмма", "Вид → График", "Макет → Объекты"], 1),
        ("Hujjatga havola qo'shish uchun qaysi tezkor tugmalar ishlatiladi?", ["Ctrl + H", "Ctrl + L", "Ctrl + K", "Ctrl + G"], 2),
        ("Hujjatdagi barcha matnni belgilash uchun qaysi tugmalar bosiladi?", ["Ctrl + C", "Ctrl + X", "Ctrl + E", "Ctrl + A"], 3),
        ("Oxirgi bajarilgan amalni bekor qilish uchun qaysi tugmalar ishlatiladi?", ["Ctrl + Z", "Ctrl + Y", "Ctrl + B", "Ctrl + R"], 0),
        ("Bekor qilingan amalni qayta tiklash uchun qaysi tugmalar ishlatiladi?", ["Ctrl + U", "Ctrl + Y", "Ctrl + P", "Ctrl + N"], 1),
        ("Hujjatni tez saqlash uchun qaysi tugmalar bosiladi?", ["Ctrl + D", "Ctrl + F", "Ctrl + S", "Ctrl + W"], 2),
        ("Matnni kursiv ko'rinishga o'tkazish uchun qaysi buyruq tanlanadi?", ["Главная → Жирный", "Главная → Зачёркнутый", "Вставка → WordArt", "Главная → Курсив"], 3),
        ("Matnning tagiga chiziq chizish uchun qaysi buyruq ishlatiladi?", ["Главная → Подчёркнутый", "Главная → Курсив", "Макет → Границы", "Вставка → Линия"], 0),
        ("Abzasni sahifa markaziga tekislash uchun qaysi buyruq tanlanadi?", ["Главная → По левому краю", "Главная → По центру", "Главная → По ширине", "Макет → По центру"], 1),
        ("Matn harflari kattaligini o'zgartirish qayerda bajariladi?", ["Вид → Масштаб", "Макет → Размер", "Главная → Размер шрифта", "Вставка → Символ"], 2),
        ("Sahifaning yuqori qismiga takrorlanuvchi yozuv qo'shish uchun qaysi buyruq ishlatiladi?", ["Вставка → Нижний колонтитул", "Главная → Заголовок", "Макет → Верх", "Вставка → Верхний колонтитул"], 3),
        ("Sahifaning pastki qismiga takrorlanuvchi yozuv qo'shish uchun qaysi buyruq ishlatiladi?", ["Вставка → Нижний колонтитул", "Вставка → Верхний колонтитул", "Макет → Низ", "Главная → Подпись"], 0),
        ("Hujjatni printerdan chiqarish uchun qaysi buyruq tanlanadi?", ["Файл → Экспорт", "Файл → Печать", "Вид → Режим чтения", "Макет → Параметры страницы"], 1),
    ],
    "Excel": [
        ("Excelda formulalar bilan ishlash uchun asosiy bo'lim qaysi?", ["Вставка", "Формулы", "Рецензирование", "Вид"], 1),
        ("Kataklardagi sonlarni qo'shish uchun qaysi funksiya ishlatiladi?", ["СУММ", "СРЗНАЧ", "СЧЁТ", "МАКС"], 0),
        ("Sonlarning o'rtacha qiymatini hisoblash uchun qaysi funksiya ishlatiladi?", ["МИН", "СУММ", "СРЗНАЧ", "ЕСЛИ"], 2),
        ("Shartga qarab turli natija chiqarish uchun qaysi funksiya ishlatiladi?", ["ИЛИ", "И", "СЧЁТ", "ЕСЛИ"], 3),
        ("Bir nechta shartning barchasi rostligini tekshirish uchun qaysi funksiya ishlatiladi?", ["И", "ИЛИ", "ЕСЛИ", "НЕ"], 0),
        ("Bir nechta shartdan hech bo'lmasa bittasi rostligini tekshirish uchun qaysi funksiya ishlatiladi?", ["И", "ИЛИ", "СУММ", "СЧЁТ"], 1),
        ("Son yozilgan kataklar miqdorini sanash uchun qaysi funksiya ishlatiladi?", ["СЧЁТЗ", "СУММ", "СЧЁТ", "СРЗНАЧ"], 2),
        ("Berilgan sonlar orasidan eng katta qiymatni topish uchun qaysi funksiya ishlatiladi?", ["МИН", "СРЗНАЧ", "СУММ", "МАКС"], 3),
        ("Berilgan sonlar orasidan eng kichik qiymatni topish uchun qaysi funksiya ishlatiladi?", ["МИН", "МАКС", "СЧЁТ", "ЕСЛИ"], 0),
        ("Tanlangan sonlarni tez yig'ish uchun qaysi buyruq ishlatiladi?", ["Главная → Сортировка", "Главная → Автосумма", "Данные → Итоги", "Формулы → Проверка ошибок"], 1),
        ("Jadval ma'lumotlaridan diagramma yaratish uchun qaysi buyruq tanlanadi?", ["Данные → Фильтр", "Формулы → Вычислить", "Вставка → Диаграммы", "Вид → Масштаб"], 2),
        ("Ma'lumotlarni alifbo yoki son bo'yicha tartiblash qayerda bajariladi?", ["Главная → Найти", "Вставка → Таблица", "Рецензирование → Защитить", "Данные → Сортировка"], 3),
        ("Faqat kerakli qiymatlarni ko'rsatish uchun qaysi buyruq ishlatiladi?", ["Данные → Фильтр", "Вид → Скрыть", "Формулы → Логические", "Главная → Очистить"], 0),
        ("Bir nechta katakni birlashtirib matnni markazga joylash uchun qaysi buyruq tanlanadi?", ["Данные → Группировать", "Главная → Объединить и поместить в центре", "Вставка → Текст", "Формулы → Объединить"], 1),
        ("Uzun matnni bitta katak ichida bir necha qatorga joylash uchun qaysi buyruq ishlatiladi?", ["Главная → Уменьшить шрифт", "Данные → Текст по столбцам", "Главная → Перенос текста", "Вид → Разметка страницы"], 2),
        ("Jadvalni pastga aylantirganda yuqori qatorni doim ko'rinadigan qilish uchun qaysi buyruq tanlanadi?", ["Главная → Закрепить", "Данные → Заголовок", "Разметка страницы → Повторить", "Вид → Закрепить верхнюю строку"], 3),
        ("Katak formatlari oynasini tez ochish uchun qaysi tugmalar bosiladi?", ["Ctrl + 1", "Ctrl + 2", "Ctrl + Shift + 1", "Alt + 1"], 0),
        ("Qaysi yozuv absolyut katak manzilini bildiradi?", ["A1", "$A$1", "A$", "1A"], 1),
        ("Qaysi yozuv nisbiy katak manzilini bildiradi?", ["$A$1", "$A1", "A1", "A$1"], 2),
        ("Excel ish kitobining zamonaviy standart kengaytmasi qaysi?", [".docx", ".pptx", ".txt", ".xlsx"], 3),
        ("Funksiyani tanlash oynasini ochish uchun qaysi buyruq ishlatiladi?", ["Формулы → Вставить функцию", "Вставка → Формула", "Главная → Функция", "Данные → Вычислить"], 0),
        ("Takrorlangan ma'lumotlarni o'chirish uchun qaysi buyruq tanlanadi?", ["Главная → Очистить", "Данные → Удалить дубликаты", "Формулы → Удалить", "Вид → Скрыть повторы"], 1),
        ("Katak qiymatiga qarab rang yoki belgi berish uchun qaysi buyruq ishlatiladi?", ["Вставка → Фигуры", "Данные → Фильтр", "Главная → Условное форматирование", "Вид → Цвет"], 2),
        ("Katakka faqat belgilangan turdagi qiymat kiritishni cheklash uchun qaysi buyruq ishlatiladi?", ["Формулы → Проверка", "Главная → Защита", "Рецензирование → Ограничить", "Данные → Проверка данных"], 3),
        ("Faqat tanlangan jadval qismini chop etish uchun qaysi buyruq tanlanadi?", ["Разметка страницы → Область печати", "Файл → Только таблица", "Вид → Область", "Данные → Печать"], 0),
        ("Sahifani albom yoki kitob ko'rinishiga o'tkazish qayerda bajariladi?", ["Вид → Ориентация", "Разметка страницы → Ориентация", "Главная → Направление", "Файл → Свойства"], 1),
        ("Excel jadvalidagi ustunlar qanday belgilanadi?", ["Faqat raqamlar bilan", "Rim raqamlari bilan", "Harflar bilan", "Belgilar bilan"], 2),
        ("Excel jadvalidagi qatorlar qanday belgilanadi?", ["Harflar bilan", "Ranglar bilan", "Belgilar bilan", "Raqamlar bilan"], 3),
        ("Jadvaldan qiymat qidirish uchun qaysi tezkor tugmalar ishlatiladi?", ["Ctrl + F", "Ctrl + G", "Ctrl + K", "Ctrl + L"], 0),
        ("Topilgan qiymatni boshqa qiymatga almashtirish oynasini ochish uchun qaysi tugmalar bosiladi?", ["Ctrl + R", "Ctrl + H", "Ctrl + T", "Ctrl + Shift + F"], 1),
    ],
    "PowerPoint": [
        ("Taqdimotga yangi slayd qo'shish uchun qaysi buyruq tanlanadi?", ["Вставка → Страница", "Главная → Создать слайд", "Дизайн → Новый", "Показ слайдов → Добавить"], 1),
        ("Slaydning matn va obyektlar joylashuvini tanlash uchun qaysi buyruq ishlatiladi?", ["Главная → Макет", "Вставка → Объект", "Дизайн → Размер слайда", "Вид → Направляющие"], 0),
        ("Slaydga rasm joylash uchun qaysi buyruq tanlanadi?", ["Дизайн → Фон", "Главная → Рисунок", "Вставка → Рисунки", "Анимация → Изображение"], 2),
        ("Slaydga geometrik shakl qo'shish uchun qaysi buyruq ishlatiladi?", ["Главная → Рисование", "Дизайн → Формы", "Переходы → Фигуры", "Вставка → Фигуры"], 3),
        ("Ma'lumotlarni grafik ko'rinishda berish uchun qaysi buyruq tanlanadi?", ["Вставка → Диаграмма", "Дизайн → График", "Вид → Диаграмма", "Анимация → Объект"], 0),
        ("Slaydga jadval qo'shish uchun qaysi buyruq ishlatiladi?", ["Главная → Таблица", "Вставка → Таблица", "Дизайн → Сетка", "Вид → Таблица"], 1),
        ("Bir slayddan ikkinchisiga o'tish effektlari qaysi bo'limda joylashgan?", ["Анимация", "Дизайн", "Переходы", "Показ слайдов"], 2),
        ("Slayd ichidagi obyektlarga harakat effekti berish qaysi bo'limda bajariladi?", ["Переходы", "Рецензирование", "Дизайн", "Анимация"], 3),
        ("Taqdimotni birinchi slayddan namoyish qilish uchun qaysi buyruq tanlanadi?", ["Показ слайдов → С начала", "Вид → Первая страница", "Главная → Начать", "Переходы → Просмотр"], 0),
        ("Taqdimotni joriy slayddan boshlash uchun qaysi buyruq ishlatiladi?", ["Показ слайдов → С начала", "Показ слайдов → С текущего слайда", "Вид → Текущий слайд", "Главная → Просмотр"], 1),
        ("Taqdimotning umumiy mavzusini tanlash qayerda bajariladi?", ["Главная → Стили", "Вставка → Тема", "Дизайн → Темы", "Вид → Образец"], 2),
        ("Slayd tomonlari o'lchamini o'zgartirish uchun qaysi buyruq tanlanadi?", ["Вид → Масштаб", "Главная → Размер", "Вставка → Страница", "Дизайн → Размер слайда"], 3),
        ("Slayd fonini o'zgartirish uchun qaysi buyruq ishlatiladi?", ["Дизайн → Формат фона", "Вставка → Заливка", "Главная → Фон", "Переходы → Цвет"], 0),
        ("Tanlangan slayddan nusxa olish uchun qaysi tezkor tugmalar ishlatiladi?", ["Ctrl + M", "Ctrl + D", "Ctrl + Shift + S", "Ctrl + Alt + D"], 1),
        ("Yangi slayd qo'shish uchun qaysi tezkor tugmalar ishlatiladi?", ["Ctrl + N", "Ctrl + Enter", "Ctrl + M", "Ctrl + L"], 2),
        ("Taqdimotni saqlash uchun qaysi tezkor tugmalar ishlatiladi?", ["Ctrl + P", "Ctrl + O", "Ctrl + W", "Ctrl + S"], 3),
        ("Oxirgi bajarilgan amalni bekor qilish uchun qaysi tugmalar bosiladi?", ["Ctrl + Z", "Ctrl + Y", "Ctrl + X", "Ctrl + B"], 0),
        ("Slaydga alohida matn maydoni qo'shish uchun qaysi buyruq tanlanadi?", ["Главная → Абзац", "Вставка → Надпись", "Дизайн → Текст", "Вид → Заметки"], 1),
        ("Slayd raqami, sana yoki pastki yozuv qo'shish uchun qaysi buyruq ishlatiladi?", ["Главная → Номер", "Дизайн → Подпись", "Вставка → Колонтитулы", "Вид → Разметка"], 2),
        ("Taqdimotga ovoz fayli qo'shish uchun qaysi buyruq tanlanadi?", ["Показ слайдов → Звук", "Анимация → Аудио", "Дизайн → Музыка", "Вставка → Звук"], 3),
        ("Taqdimotga video joylash uchun qaysi buyruq ishlatiladi?", ["Вставка → Видео", "Показ слайдов → Фильм", "Анимация → Видео", "Дизайн → Медиа"], 0),
        ("Slayd uchun ma'ruzachi izohlarini yozish maydoni nima deb ataladi?", ["Комментарии", "Заметки", "Колонтитулы", "Подписи"], 1),
        ("Barcha slaydlar uchun umumiy dizayn va joylashuvni o'zgartirish qayerda bajariladi?", ["Дизайн → Темы", "Главная → Макет", "Вид → Образец слайдов", "Переходы → Параметры"], 2),
        ("Bir nechta obyektni bitta guruhga birlashtirish uchun qaysi tugmalar ishlatiladi?", ["Ctrl + D", "Ctrl + J", "Ctrl + Shift + G", "Ctrl + G"], 3),
        ("Guruhlangan obyektlarni ajratish uchun qaysi tugmalar ishlatiladi?", ["Ctrl + Shift + G", "Ctrl + Alt + G", "Ctrl + U", "Ctrl + Shift + D"], 0),
        ("Obyektlarni bir chiziq bo'ylab tekislash uchun qaysi buyruq ishlatiladi?", ["Главная → Абзац", "Формат фигуры → Выровнять", "Вид → Линейка", "Дизайн → Расположение"], 1),
        ("Namoyish vaqtida qora ekran chiqarish uchun qaysi tugma bosiladi?", ["W", "Esc", "B", "F5"], 2),
        ("Slayd namoyishini to'xtatish uchun qaysi tugma bosiladi?", ["Enter", "Tab", "Delete", "Esc"], 3),
        ("Slaydlarni kichik ko'rinishda tartiblash uchun qaysi rejim tanlanadi?", ["Вид → Сортировщик слайдов", "Вид → Режим чтения", "Показ слайдов → Настройка", "Главная → Упорядочить"], 0),
        ("PowerPoint taqdimotining zamonaviy standart kengaytmasi qaysi?", [".xlsx", ".pptx", ".docx", ".pdf"], 1),
    ],
}
