from .seed_python import PYTHON_TESTS


IT_TESTS = {
    "HTML CSS": [
        ("HTML so'zining to'liq ma'nosi qaysi?", ["Hyper Text Markup Language", "High Text Making Language", "Hyper Tool Markup Language", "Home Text Markup Language"], 0),
        ("CSS nima uchun ishlatiladi?", ["Saytni bezash uchun", "Ma'lumotlar bazasi yaratish uchun", "Dasturlash uchun", "Server yaratish uchun"], 0),
        ("HTML nima?", ["Dasturlash tili", "Veb sahifa yaratish uchun belgilash tili", "Operatsion tizim", "Grafik dastur"], 1),
        ("font-family nima vazifani bajaradi?", ["Matn shriftini o'zgartiradi", "Matn rangini o'zgartiradi", "Matnni markazlaydi", "Balandligini o'zgartiradi"], 0),
        ("<a> tegi nima uchun ishlatiladi?", ["Jadval yaratish", "Havola (link) yaratish", "Rasm chiqarish", "Tugma yaratish"], 1),
        ("margin nima qiladi?", ["Ichki bo'shliq beradi", "Tashqi bo'shliq beradi", "Rang beradi", "Chegara chizadi"], 1),
        ("Sarlavha teglari qaysi javobda to'g'ri ko'rsatilgan?", ["h1 dan h2 gacha", "h1 dan h4 gacha", "h1 dan h6 gacha", "h2 dan h6 gacha"], 2),
        ("color nima vazifani bajaradi?", ["Matn rangini o'zgartiradi", "Fon rangini o'zgartiradi", "Kenglik beradi", "Balandlik beradi"], 0),
        ("<img> tegi nima uchun ishlatiladi?", ["Tugma yaratadi", "Rasm chiqaradi", "Jadval yaratadi", "Video chiqaradi"], 1),
        ("display: flex nima qiladi?", ["Elementlarni moslashuvchan joylashtiradi", "Rasm chiqaradi", "Jadval yaratadi", "Matn yozadi"], 0),
        ("alt atributining vazifasi nima?", ["Rasm tavsifini yozadi", "Rasmni kattalashtiradi", "Link yaratadi", "Rang beradi"], 0),
        ("padding nima qiladi?", ["Ichki bo'shliq beradi", "Tashqi bo'shliq beradi", "Rang beradi", "Chegara chizadi"], 0),
        ("<p> tegi nima uchun ishlatiladi?", ["Jadval yaratadi", "Paragraf yaratadi", "Video chiqaradi", "Tugma yaratadi"], 1),
        ("justify-content nima vazifani bajaradi?", ["Elementlarni asosiy o'q bo'ylab joylashtiradi", "Elementlarni ko'ndalang o'q bo'ylab joylashtiradi", "Rang beradi", "Kenglik beradi"], 0),
        ("Link manzili qaysi atribut orqali yoziladi?", ["src", "href", "alt", "class"], 1),
        ("background-color nima qiladi?", ["Matn rangini o'zgartiradi", "Fon rangini o'zgartiradi", "Chegara beradi", "Balandlik beradi"], 1),
        ("<button> tegi nima uchun ishlatiladi?", ["Tugma yaratadi", "Rasm chiqaradi", "Jadval yaratadi", "Link yaratadi"], 0),
        ("width nima vazifani bajaradi?", ["Kenglik beradi", "Balandlik beradi", "Rang beradi", "Ichki bo'shliq beradi"], 0),
        ("HTML atributi nima?", ["CSS kodi", "Tegga qo'shimcha ma'lumot beradi", "JavaScript kodi", "Dasturlash tili"], 1),
        ("font-size nima qiladi?", ["Matn o'lchamini o'zgartiradi", "Rang beradi", "Kenglik beradi", "Chegara beradi"], 0),
        ("input tegi nima uchun ishlatiladi?", ["Matn kiritish maydoni yaratadi", "Jadval yaratadi", "Rasm chiqaradi", "Video chiqaradi"], 0),
        ("align-items nima qiladi?", ["Elementlarni ko'ndalang o'q bo'ylab tekislaydi", "Elementlarni asosiy o'q bo'ylab tekislaydi", "Rang beradi", "Margin beradi"], 0),
        ("HTML faylining kengaytmasi qanday?", [".css", ".js", ".html", ".png"], 2),
        ("border nima vazifani bajaradi?", ["Chegara chizadi", "Rang beradi", "Tashqi bo'shliq beradi", "Ichki bo'shliq beradi"], 0),
        ("<h1> tegi nima uchun ishlatiladi?", ["Eng katta sarlavha yozish", "Rasm chiqarish", "Tugma yaratish", "Link yaratish"], 0),
        ("font-weight nima qiladi?", ["Matnni qalinlashtiradi", "Rang beradi", "Balandlik beradi", "Kenglik beradi"], 0),
        ("flex-direction: row nimani bildiradi?", ["Elementlar yonma-yon joylashadi", "Elementlar ustma-ust joylashadi", "Rang beradi", "Jadval yaratadi"], 0),
        ("src atributi nima uchun ishlatiladi?", ["Rasm manzilini ko'rsatadi", "Link yaratadi", "Rang beradi", "Matn yozadi"], 0),
        ("height nima vazifani bajaradi?", ["Element balandligini belgilaydi", "Element kengligini belgilaydi", "Rang beradi", "Matnni qalinlashtiradi"], 0),
        ("border-radius nima qiladi?", ["Burchaklarni yumaloqlaydi", "Chegara chizadi", "Rang beradi", "Ichki bo'shliq beradi"], 0),
        ("flex-direction: column nimani bildiradi?", ["Elementlar ustma-ust joylashadi", "Elementlar yonma-yon joylashadi", "Rang beradi", "Jadval yaratadi"], 0),
        ("<img> tegi ishlashi uchun eng muhim atribut qaysi?", ["class", "target", "src", "href"], 2),
        (":hover nima?", ["Sichqoncha element ustiga olib borilganda ishlaydi", "Element bosilganda ishlaydi", "Sahifa yuklanganda ishlaydi", "Matnni qalinlashtiradi"], 0),
        ("transition nima uchun ishlatiladi?", ["Animatsiyani silliq bajarish uchun", "Rasm chiqarish uchun", "Jadval yaratish uchun", "Matn yozish uchun"], 0),
        ("Saytning yuqori qismi qaysi teg orqali yoziladi?", ["<footer>", "<header>", "<main>", "<section>"], 1),
        ("Saytning o'rta qismi qaysi teg orqali yoziladi?", ["<header>", "<main>", "<footer>", "<nav>"], 1),
        ("Saytning pastki qismi qaysi teg orqali yoziladi?", ["<section>", "<footer>", "<header>", "<aside>"], 1),
        ("Odatda <section> tegidan keyin nima yoziladi?", ["<div class=\"container\">", "<img>", "<button>", "<video>"], 0),
        (".container nima uchun ishlatiladi?", ["Kontentni tartibli joylashtirish va markazga olib kelish uchun", "Rasm chiqarish uchun", "Video qo'shish uchun", "Jadval yaratish uchun"], 0),
        ("display: flex nima vazifani bajaradi?", ["Elementlarni moslashuvchan joylashtiradi", "Matn rangini o'zgartiradi", "Chegara chizadi", "Rasm chiqaradi"], 0),
    ],
    "JavaScript": [
        ("Natija nima?\nlet x = 5;\nif (x++ === 5) {\n  x += 2;\n}\nconsole.log(x);", ["5", "6", "7", "8"], 3),
        ("Natija nima?\nlet arr = [1, 2, 3, 4];\nlet result = arr.filter(x => x % 2 === 0).map(x => x * 3);\nconsole.log(result);", ["[2, 4]", "[3, 9]", "[1, 2, 3, 4]", "[6, 12]"], 3),
        ("Natija nima?\nlet a = 10;\nlet b = \"10\";\nconsole.log(a == b);\nconsole.log(a === b);", ["true false", "false false", "true true", "false true"], 0),
        ("Natija nima?\nfunction test(x) {\n  if (x > 5) return x * 2;\n  return x + 2;\n}\nconsole.log(test(4));", ["4", "6", "8", "10"], 1),
        ("Natija nima?\nlet sum = 0;\nfor (let i = 1; i <= 5; i++) {\n  if (i % 2 === 0) sum += i;\n}\nconsole.log(sum);", ["10", "9", "6", "15"], 2),
        ("Natija nima?\nlet x = 10;\nlet y = x > 5 ? 20 : 30;\nconsole.log(y);", ["10", "20", "30", "undefined"], 1),
        ("Natija nima?\nlet arr = [10, 20, 30];\nconsole.log(arr.pop());\nconsole.log(arr.length);", ["30 va 3", "20 va 2", "10 va 2", "30 va 2"], 3),
        ("Natija nima?\nlet x = 0;\nwhile (x < 3) {\n  x++;\n}\nconsole.log(x);", ["2", "3", "4", "0"], 1),
        ("Natija nima?\nconsole.log(!false && true);", ["true", "false", "undefined", "null"], 0),
        ("Natija nima?\nlet nums = [1, 2, 3];\nlet result = nums.map(x => x + 1);\nconsole.log(nums);\nconsole.log(result);", ["[2,3,4] va [2,3,4]", "[1,2,3] va [1,2,3]", "[1,2,3] va [2,3,4]", "[2,3,4] va [1,2,3]"], 2),
        ("Natija nima?\nfunction add(a = 2, b = 3) {\n  return a + b;\n}\nconsole.log(add(5));", ["5", "7", "8", "undefined"], 2),
        ("Natija nima?\nlet x = null;\nconsole.log(typeof x);", ["null", "undefined", "object", "string"], 2),
        ("Natija nima?\nlet arr = [1, 2, 3, 4, 5];\nconsole.log(arr.slice(1, 4));", ["[1,2,3]", "[2,3,4]", "[2,3,4,5]", "[1,2,3,4]"], 1),
        ("Natija nima?\nlet x = 5;\nlet y = 10;\nconsole.log(x > 3 && y < 5 || y === 10);", ["false", "5", "true", "undefined"], 2),
        ("Natija nima?\nlet a = 1;\nfor (let i = 0; i < 3; i++) {\n  a *= 2;\n}\nconsole.log(a);", ["4", "6", "8", "16"], 2),
        ("Natija nima?\nlet text = \"JavaScript\";\nconsole.log(text.includes(\"Script\"));", ["true", "false", "Script", "undefined"], 0),
        ("Natija nima?\nlet arr = [1, 2, 3];\narr.push(4);\narr.shift();\nconsole.log(arr);", ["[1,2,3,4]", "[2,3,4]", "[1,2,3]", "[2,3]"], 1),
        ("Natija nima?\nlet x = 10;\nif (x > 5) {\n  if (x < 15) console.log(\"A\");\n  else console.log(\"B\");\n}", ["B", "10", "A", "Error"], 2),
        ("Natija nima?\nlet result = [1, 2, 3, 4].filter(x => x > 2);\nconsole.log(result.length);", ["1", "2", "3", "4"], 1),
        ("Natija nima?\nfunction check(x) {\n  return x % 2 === 0 ? \"juft\" : \"toq\";\n}\nconsole.log(check(7));", ["juft", "7", "toq", "false"], 2),
        ("Natija nima?\nlet a = 5;\nlet b = ++a;\nconsole.log(a, b);", ["5 6", "6 5", "6 6", "5 5"], 2),
        ("Natija nima?\nlet a = 5;\nlet b = a++;\nconsole.log(a, b);", ["6 5", "5 6", "6 6", "5 5"], 0),
        ("Natija nima?\nconsole.log(0 || \"Salom\");", ["0", "false", "undefined", "Salom"], 3),
        ("Natija nima?\nconsole.log(\"\" || 25);", ["\"\"", "25", "false", "undefined"], 1),
        ("Natija nima?\nlet arr = [2, 4, 6];\nconsole.log(arr.includes(4));", ["true", "false", "4", "2"], 0),
        ("Natija nima?\nlet x = 3;\nswitch (x) {\n  case 1: console.log(\"A\"); break;\n  case 2: console.log(\"B\"); break;\n  case 3: console.log(\"C\"); break;\n  default: console.log(\"D\");\n}", ["A", "B", "C", "D"], 2),
        ("Natija nima?\nlet sum = 0;\nfor (let i = 0; i < 5; i++) {\n  if (i === 3) continue;\n  sum += i;\n}\nconsole.log(sum);", ["10", "7", "6", "3"], 1),
        ("Natija nima?\nlet arr = [1, 2, 3];\nlet result = arr.map(x => x * x).filter(x => x > 4);\nconsole.log(result);", ["[1,4,9]", "[4,9]", "[9]", "[1,9]"], 2),
        ("Natija nima?\nfunction test() {\n  let x = 10;\n  return x > 5 && x < 20;\n}\nconsole.log(test());", ["10", "false", "true", "undefined"], 2),
        ("Natija nima?\nlet arr = [1, 2, 3];\nlet x = arr.pop();\narr.unshift(x);\nconsole.log(arr);", ["[3,1,2]", "[1,2,3]", "[2,3,1]", "[3,2,1]"], 0),
    ],
    "Vue": [
        ("Vue 3 da ref() nima uchun ishlatiladi?", ["CSS yozish uchun", "API yaratish uchun", "Reaktiv qiymat yaratish uchun", "Komponentni o'chirish uchun"], 2),
        ("Quyidagi kod natijasi nima bo'ladi?\nconst count = ref(0)\ncount.value++", ["count.value 1 bo'ladi", "count 2 bo'ladi", "Xatolik beradi", "count 0 bo'lib qoladi"], 0),
        ("computed() ning asosiy vazifasi nima?", ["Eventlarni bloklash", "Hosilaviy qiymatni hisoblash va cache qilish", "API server yaratish", "Komponentni qayta yuklash"], 1),
        ("Vue'da v-if nima qiladi?", ["Array yaratadi", "Elementga class qo'shadi", "Input qiymatini bog'laydi", "Shart asosida elementni DOMga qo'shadi yoki olib tashlaydi"], 3),
        ("v-for ishlatilganda :key nima uchun kerak?", ["Vue'ga elementlarni samarali kuzatishga yordam berish uchun", "API yuborish uchun", "Event yaratish uchun", "Element rangini o'zgartirish uchun"], 0),
        ("v-model asosan nima uchun ishlatiladi?", ["CSS animatsiya", "Lifecycle boshqarish", "Komponentni import qilish", "Ikki tomonlama data binding"], 3),
        ("Vue 3 Composition API'da onMounted() qachon ishlaydi?", ["Faqat button bosilganda", "Komponent DOMga mount qilingandan keyin", "Komponent o'chirilganda", "Komponent yaratishdan oldin"], 1),
        ("props nima uchun ishlatiladi?", ["Router yaratish uchun", "CSS ulash uchun", "Parent komponentdan child komponentga ma'lumot uzatish uchun", "Child komponentdan parentga ma'lumot yuborish uchun"], 2),
        ("Child komponent parentga hodisa yuborish uchun odatda nimadan foydalanadi?", ["watch", "emit", "provide", "computed"], 1),
        ("Quyidagi kodda count ning qiymatini olish uchun nima yoziladi?\nconst count = ref(10)", ["count.get()", "count.data", "count.ref", "count.value"], 3),
        ("reactive() qaysi maqsadda ishlatiladi?", ["Route yaratish uchun", "Ob'ektni reaktiv qilish uchun", "Componentni import qilish uchun", "Oddiy string yaratish uchun"], 1),
        ("watch() ning vazifasi nima?", ["Template yaratish", "CSS o'zgartirish", "Reactive qiymatdagi o'zgarishlarni kuzatish", "Componentni import qilish"], 2),
        ("Quyidagilardan qaysi biri Vue template ichida to'g'ri yozilgan?", ["<button click=\"@add\">Add</button>", "<button event-click=\"add\">Add</button>", "<button @click=\"add\">Add</button>", "<button onclick=\"add()\">Add</button>"], 2),
        ("v-bind ning qisqa yozilishi qaysi?", [":", "$", "@", "#"], 0),
        ("v-on:click ning qisqa ko'rinishi qaysi?", ["#click", "$click", ":click", "@click"], 3),
        ("Quyidagi computed qanday ishlaydi?\nconst total = computed(() => price.value * quantity.value)", ["Kod xato", "price yoki quantity o'zgarsa, total qayta hisoblanadi", "total hech qachon o'zgarmaydi", "total faqat bir marta hisoblanadi"], 1),
        ("Vue komponentida template nima uchun ishlatiladi?", ["Ma'lumotlar bazasini ulash uchun", "Server yaratish uchun", "HTML interfeysini tasvirlash uchun", "JavaScript modulini eksport qilish uchun"], 2),
        ("Vue 3 Composition API'da setup() ning vazifasi nima?", ["CSS fayl yaratish", "Componentning Composition API logikasini tashkil qilish", "Routerni avtomatik o'rnatish", "Browserni ochish"], 1),
        ("Quyidagilardan qaysi biri v-for uchun to'g'ri?\n<li v-for=\"item in items\" :key=\"item.id\">{{ item.name }}</li>", ["items ni o'chiradi", "Xatolik beradi", "Faqat bitta element chiqaradi", "items ichidagi elementlarni chiqaradi"], 3),
        ("v-show va v-if orasidagi asosiy farq nima?", ["v-show CSS orqali ko'rsatish/yashirishni boshqaradi", "Ular orasida farq yo'q", "v-if faqat CSS bilan ishlaydi", "v-show elementni DOMdan olib tashlaydi"], 0),
        ("defineProps() Vue 3 <script setup> ichida nima uchun ishlatiladi?", ["State'ni o'chirish uchun", "Propslarni e'lon qilish uchun", "Router yaratish uchun", "Event yaratish uchun"], 1),
        ("defineEmits() nima uchun ishlatiladi?", ["CSS ulash uchun", "API chaqirish uchun", "Component emit qiladigan eventlarni e'lon qilish uchun", "Propslarni o'qish uchun"], 2),
        ("Quyidagi kodda qaysi holatda watch ishga tushadi?\nwatch(count, () => { console.log('changed') })", ["Faqat console.log chaqirilganda", "Component o'chirilganda", "count o'zgarganda", "Sahifa ochilganda har doim"], 2),
        ("Vue'da nextTick() nima uchun ishlatiladi?", ["Componentni o'chirish uchun", "API'ni qayta ishga tushirish uchun", "Keyingi JavaScript faylini yuklash uchun", "DOM yangilanishi tugagandan keyin kod bajarilishini kutish uchun"], 3),
        ("Quyidagi kod nima qiladi?\n<input v-model=\"name\">\n<p>{{ name }}</p>", ["name avtomatik o'chadi", "Faqat <p> ishlaydi", "Inputdagi qiymat name bilan bog'lanadi", "Input ishlamaydi"], 2),
        ("Parent komponentdan child komponentga title yuborishning to'g'ri usuli qaysi?", ["<Child emit=\"title\" />", "<Child title=\"Hello\" />", "<Child props.title=\"Hello\" />", "<Child :send=\"title\" />"], 1),
        ("Vue'da ref bilan primitive qiymat ishlatilganda qaysi xususiyat muhim?", ["ref faqat object bilan ishlaydi", "Qiymat .data orqali olinadi", "ref reaktiv emas", "Qiymat .value orqali olinadi/o'zgartiriladi"], 3),
        ("onUnmounted() qachon chaqiriladi?", ["Faqat API javob berganda", "Component yaratilishidan oldin", "Component DOMdan olib tashlangandan keyin", "Har bir click eventida"], 2),
        ("Quyidagi kodda isLoggedIn true bo'lsa nima chiqadi?\n<div v-if=\"isLoggedIn\">Welcome</div>\n<div v-else>Login</div>", ["Ikkalasi ham", "Welcome", "Login", "Hech narsa"], 1),
        ("Quyidagi variantlardan qaysi biri Vue 3 Composition API uchun eng to'g'ri?\nconst price = ref(10)\nconst count = ref(2)\nconst total = computed(() => price.value * count.value)", ["computed faqat template tashqarisida ishlaydi", "ref qiymatlari reaktiv emas", "total qiymati price yoki count o'zgarganda avtomatik yangilanadi", "total hech qachon yangilanmaydi"], 2),
    ],
    "Python": PYTHON_TESTS,
}
